import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { DishEntity } from '../../../../../modules/dishes/infrastructure/persistence/relational/entities/dish.entity';
import { DishStatus, FoodType } from '../../../../../modules/dishes/enums/dish.enum';

@Injectable()
export class DishSeedService {
  constructor(
    @InjectRepository(DishEntity)
    private readonly repository: Repository<DishEntity>,
  ) {}

  async run(): Promise<void> {
    const count = await this.repository.count();
    if (count > 0) return;

    const dishes: Partial<DishEntity>[] = [
      { restaurantId: 1, scanId: 1, name: 'Avocado Toast', description: 'Creamy avocado on sourdough with microgreens and cherry tomatoes', foodType: FoodType.VEGAN, imageUrl: ['https://foodsharingvegan.com/wp-content/uploads/2023/01/Rhodes-Avocado-Toast-Plant-Based-on-a-Budget-1-2.jpg'], ingredients: ['avocado', 'sourdough', 'cherry tomatoes', 'microgreens', 'lemon'], menuCategory: 'Starter', cuisineType: 'Continental', isVegan: true, ratings: 5, tags: 'popular', price: 350, status: DishStatus.ACTIVE },
      { restaurantId: 2, scanId: 2, name: 'Masala Dosa', description: 'Crispy rice crepe filled with spiced potato masala', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc'], ingredients: ['rice batter', 'potato', 'onion', 'mustard seeds', 'curry leaves'], menuCategory: 'Main', cuisineType: 'Indian', isVegan: false, ratings: 4, tags: 'Must-try', price: 180, status: DishStatus.ACTIVE },
      { restaurantId: 3, scanId: 3, name: 'Pad Thai', description: 'Stir-fried rice noodles with tofu, peanuts, and tamarind sauce', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1559314809-0d155014e29e'], ingredients: ['rice noodles', 'tofu', 'peanuts', 'tamarind', 'bean sprouts', 'lime'], menuCategory: 'Main', cuisineType: 'Chinese', isVegan: true, ratings: 5, tags: 'chef-special', price: 450, status: DishStatus.ACTIVE },
      { restaurantId: 4, scanId: 4, name: 'Acai Bowl', description: 'Blended acai topped with granola, banana, and berries', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1590301157890-4810ed352733'], ingredients: ['acai', 'banana', 'granola', 'blueberries', 'chia seeds', 'coconut flakes'], menuCategory: 'Dessert', cuisineType: 'Continental', isVegan: true, ratings: 4, tags: 'healthy', price: 380, status: DishStatus.ACTIVE },
      { restaurantId: 5, scanId: 5, name: 'Chole Bhature', description: 'Spicy chickpea curry served with deep-fried puffed bread', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1626132647523-66f5bf380027'], ingredients: ['chickpeas', 'onion', 'tomato', 'ginger', 'garlic', 'refined flour'], menuCategory: 'Main', cuisineType: 'Indian', isVegan: false, ratings: 4, tags: 'spicy', price: 200, status: DishStatus.ACTIVE },
      { restaurantId: 6, scanId: 6, name: 'White Sauce Pasta', description: 'Creamy penne pasta with garlic, mushrooms, and herbs', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9'], ingredients: ['penne', 'cream', 'garlic', 'mushrooms', 'parsley', 'parmesan'], menuCategory: 'Main', cuisineType: 'Italian', isVegan: false, ratings: 4, tags: 'popular', price: 420, status: DishStatus.ACTIVE },
      { restaurantId: 7, scanId: 7, name: 'Green Smoothie', description: 'Fresh spinach, kale, banana, and pineapple blended smoothie', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1610970881699-44a5587cabec'], ingredients: ['spinach', 'kale', 'banana', 'pineapple', 'almond milk'], menuCategory: 'Mocktail', cuisineType: 'Continental', isVegan: true, ratings: 3, tags: 'healthy', price: 250, status: DishStatus.ACTIVE },
      { restaurantId: 8, scanId: 8, name: 'Vegan Burrito', description: 'Loaded burrito with black beans, rice, guacamole, and salsa', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1626700051175-6818013e1d4f'], ingredients: ['tortilla', 'black beans', 'rice', 'guacamole', 'salsa', 'jalapeños'], menuCategory: 'Main', cuisineType: 'Mexican', isVegan: true, ratings: 4, tags: 'Must-try', price: 380, status: DishStatus.ACTIVE },
      { restaurantId: 9, scanId: 9, name: 'Idli Sambar', description: 'Steamed rice cakes served with lentil soup and chutneys', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1589301760014-d929f3979dbc'], ingredients: ['rice', 'urad dal', 'toor dal', 'vegetables', 'tamarind'], menuCategory: 'Starter', cuisineType: 'Indian', isVegan: true, ratings: 3, tags: 'healthy', price: 120, status: DishStatus.ACTIVE },
      { restaurantId: 10, scanId: 10, name: 'Kung Pao Tofu', description: 'Spicy stir-fried tofu with peanuts and Sichuan peppers', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1512058564366-18510be2db19'], ingredients: ['tofu', 'peanuts', 'sichuan pepper', 'soy sauce', 'bell peppers', 'spring onion'], menuCategory: 'Main', cuisineType: 'Chinese', isVegan: true, ratings: 5, tags: 'spicy', price: 380, status: DishStatus.ACTIVE },
      { restaurantId: 11, scanId: 11, name: 'Vegan Chocolate Cake', description: 'Rich dark chocolate cake made without eggs or dairy', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1578985545062-69928b1d9587'], ingredients: ['dark chocolate', 'almond milk', 'coconut oil', 'flour', 'sugar', 'cocoa'], menuCategory: 'Dessert', cuisineType: 'Continental', isVegan: true, ratings: 5, tags: 'chef-special', price: 320, status: DishStatus.ACTIVE },
      { restaurantId: 12, scanId: 12, name: 'Margherita Pizza', description: 'Classic pizza with fresh basil, mozzarella, and tomato sauce', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1574071318508-1cdbab80d002'], ingredients: ['pizza dough', 'tomato sauce', 'mozzarella', 'basil', 'olive oil'], menuCategory: 'Main', cuisineType: 'Italian', isVegan: false, ratings: 4, tags: 'popular', price: 450, status: DishStatus.ACTIVE },
      { restaurantId: 13, scanId: 13, name: 'Millet Pongal', description: 'Warm millet pongal tempered with ghee and cashews', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1630383249896-424e482df921'], ingredients: ['millet', 'moong dal', 'ghee', 'cashews', 'cumin', 'pepper'], menuCategory: 'Main', cuisineType: 'Indian', isVegan: false, ratings: 3, tags: 'healthy', price: 160, status: DishStatus.ACTIVE },
      { restaurantId: 14, scanId: 14, name: 'Quinoa Buddha Bowl', description: 'Nourishing bowl with quinoa, roasted veggies, tahini dressing', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1512621776951-a57141f2eefd'], ingredients: ['quinoa', 'sweet potato', 'chickpeas', 'kale', 'tahini', 'avocado'], menuCategory: 'Main', cuisineType: 'Continental', isVegan: true, ratings: 5, tags: 'Must-try', price: 480, status: DishStatus.ACTIVE },
      { restaurantId: 15, scanId: 15, name: 'Tiramisu', description: 'Vegan tiramisu with cashew cream and espresso-soaked ladyfingers', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1571877227200-a0d98ea607e9'], ingredients: ['cashew cream', 'espresso', 'cocoa', 'coconut cream', 'vanilla'], menuCategory: 'Dessert', cuisineType: 'Italian', isVegan: true, ratings: 5, tags: 'chef-special', price: 380, status: DishStatus.ACTIVE },
      { restaurantId: 16, scanId: 16, name: 'Paneer Tikka', description: 'Spicy paneer tikka marinated in yogurt and grilled in tandoor', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1599487488170-d11ec9c172f0'], ingredients: ['paneer', 'yogurt', 'cardamom', 'green chilli', 'lemon', 'almonds'], menuCategory: 'Starter', cuisineType: 'Indian', isVegan: false, ratings: 4, tags: 'spicy', price: 320, status: DishStatus.ACTIVE },
      { restaurantId: 17, scanId: 17, name: 'Falafel Wrap', description: 'Crispy falafel with hummus, pickled veggies in warm pita', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1529006557810-274b9b2fc783'], ingredients: ['chickpeas', 'tahini', 'pita', 'cucumber', 'tomato', 'pickled turnip'], menuCategory: 'Main', cuisineType: 'Continental', isVegan: true, ratings: 4, tags: 'popular', price: 280, status: DishStatus.ACTIVE },
      { restaurantId: 18, scanId: 18, name: 'Thali Deluxe', description: 'Complete Indian thali with dal, sabzi, roti, rice, and dessert', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1585937421612-70a008356fbe'], ingredients: ['dal', 'seasonal vegetables', 'roti', 'rice', 'raita', 'pickle'], menuCategory: 'Main', cuisineType: 'Indian', isVegan: false, ratings: 4, tags: 'Must-try', price: 250, status: DishStatus.ACTIVE },
      { restaurantId: 19, scanId: 19, name: 'Matcha Latte', description: 'Ceremonial grade matcha whisked with oat milk', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1536256263959-770b48d82b0a'], ingredients: ['matcha powder', 'oat milk', 'vanilla', 'agave'], menuCategory: 'Mocktail', cuisineType: 'Continental', isVegan: true, ratings: 4, tags: 'healthy', price: 280, status: DishStatus.ACTIVE },
      { restaurantId: 20, scanId: 20, name: 'Mushroom Risotto', description: 'Creamy arborio rice with wild mushrooms and truffle oil', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1476124369491-e7addf5db371'], ingredients: ['arborio rice', 'wild mushrooms', 'truffle oil', 'vegetable stock', 'onion'], menuCategory: 'Main', cuisineType: 'Italian', isVegan: true, ratings: 5, tags: 'chef-special', price: 520, status: DishStatus.ACTIVE },
      { restaurantId: 21, scanId: 21, name: 'Aloo Gobi', description: 'Spiced cauliflower and potato curry with aromatic spices', foodType: FoodType.VEG, imageUrl: ['https://images.unsplash.com/photo-1505253758473-96b7015fcd40'], ingredients: ['cauliflower', 'potato', 'turmeric', 'cumin', 'coriander', 'ginger'], menuCategory: 'Main', cuisineType: 'Indian', isVegan: true, ratings: 3, tags: 'healthy', price: 220, status: DishStatus.INACTIVE },
      { restaurantId: 22, scanId: 22, name: 'Mediterranean Mezze Platter', description: 'Assorted dips with hummus, baba ganoush, and fresh pita', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1540189549336-e6e99c3679fe'], ingredients: ['hummus', 'baba ganoush', 'pita', 'olives', 'sundried tomatoes', 'feta'], menuCategory: 'Starter', cuisineType: 'Continental', isVegan: true, ratings: 5, tags: 'Must-try', price: 550, status: DishStatus.ACTIVE },
      { restaurantId: 23, scanId: 23, name: 'Vegan Tacos', description: 'Corn tortillas loaded with jackfruit carnitas and fresh salsa', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1551504734-5ee1c4a1479b'], ingredients: ['corn tortilla', 'jackfruit', 'avocado', 'salsa verde', 'cilantro', 'lime'], menuCategory: 'Main', cuisineType: 'Mexican', isVegan: true, ratings: 4, tags: 'popular', price: 350, status: DishStatus.ACTIVE },
      { restaurantId: 24, scanId: 24, name: 'Mushroom Pizza', description: 'Wood-fired pizza with truffle mushroom and vegan cheese', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1513104890138-7c749659a591'], ingredients: ['pizza dough', 'truffle mushroom', 'vegan cheese', 'arugula', 'olive oil'], menuCategory: 'Main', cuisineType: 'Italian', isVegan: true, ratings: 5, tags: 'chef-special', price: 580, status: DishStatus.ACTIVE },
      { restaurantId: 25, scanId: 25, name: 'Cold Pressed Juice Flight', description: 'Selection of 4 seasonal cold-pressed juices', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1622597467836-f3285f2131b8'], ingredients: ['beetroot', 'carrot', 'ginger', 'apple', 'celery', 'turmeric'], menuCategory: 'Mocktail', cuisineType: 'Continental', isVegan: true, ratings: 4, tags: 'healthy', price: 420, status: DishStatus.ACTIVE },
      { restaurantId: 26, scanId: 26, name: 'Vegan Biryani', description: 'Fragrant basmati rice layered with spiced vegetables and saffron', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8'], ingredients: ['basmati rice', 'mixed vegetables', 'saffron', 'biryani masala', 'mint', 'cashews'], menuCategory: 'Main', cuisineType: 'Indian', isVegan: true, ratings: 4, tags: 'Must-try', price: 350, status: DishStatus.ACTIVE },
      { restaurantId: 27, scanId: 27, name: 'Pesto Flatbread', description: 'Crispy flatbread with basil pesto, sun-dried tomatoes, and pine nuts', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1565299624946-b28f40a0ae38'], ingredients: ['flatbread', 'basil pesto', 'sun-dried tomatoes', 'pine nuts', 'arugula'], menuCategory: 'Starter', cuisineType: 'Italian', isVegan: true, ratings: 4, tags: 'popular', price: 380, status: DishStatus.ACTIVE },
      { restaurantId: 28, scanId: 28, name: 'Enchiladas Verdes', description: 'Corn tortillas filled with beans, topped with green salsa', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1534352956036-cd81e27dd615'], ingredients: ['corn tortillas', 'black beans', 'tomatillo salsa', 'cashew cream', 'jalapeños'], menuCategory: 'Main', cuisineType: 'Mexican', isVegan: true, ratings: 4, tags: 'spicy', price: 400, status: DishStatus.OUT_OF_STOCK },
      { restaurantId: 29, scanId: 29, name: 'Chaat Platter', description: 'Assorted vegan street food chaats with tangy chutneys', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1601050690117-94f5f6fa8bd7'], ingredients: ['potato', 'chickpeas', 'puffed rice', 'tamarind chutney', 'mint chutney', 'sev'], menuCategory: 'Starter', cuisineType: 'Indian', isVegan: true, ratings: 4, tags: 'popular', price: 200, status: DishStatus.ACTIVE },
      { restaurantId: 30, scanId: 30, name: 'Cinnamon Roll', description: 'Warm vegan cinnamon roll with cream cheese frosting', foodType: FoodType.VEGAN, imageUrl: ['https://images.unsplash.com/photo-1509365390695-33aee754301f'], ingredients: ['flour', 'cinnamon', 'brown sugar', 'vegan butter', 'cashew cream cheese'], menuCategory: 'Dessert', cuisineType: 'Continental', isVegan: true, ratings: 5, tags: 'chef-special', price: 280, status: DishStatus.ACTIVE },
    ];

    await this.repository.save(this.repository.create(dishes));
  }
}
