import { Injectable } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';

import { RestaurantEntity } from '../../../../../modules/restaurants/infrastructure/persistence/relational/entities/restaurant.entity';

@Injectable()
export class RestaurantSeedService {
  constructor(
    @InjectRepository(RestaurantEntity)
    private readonly repository: Repository<RestaurantEntity>,
  ) {}

  async run(): Promise<void> {
    const count = await this.repository.count();
    if (count > 0) return;

    const restaurants: Partial<RestaurantEntity>[] = [
      // Chennai — 15 restaurants
      { name: 'Carrots', city: 'Chennai', state: 'Tamil Nadu', address: 'No.45, Khader Nawaz Khan Rd, Nungambakkam', latitude: 13.06015, longitude: 80.24286, phoneNumber: '+914428331234', cuisineType: ['Vegan', 'Health Food'], priceRange: 2, rating: 4.6, totalReviews: 128, description: 'Pure vegan restaurant with organic ingredients', tags: ['vegan', 'organic', 'delivery'], source: 'google', isVerified: true, openingHours: { mon: '10am-10pm', tue: '10am-10pm', wed: '10am-10pm', thu: '10am-10pm', fri: '10am-10pm', sat: '10am-11pm', sun: '10am-11pm' } },
      { name: 'The Green Plate', city: 'Chennai', state: 'Tamil Nadu', address: '12, Anna Salai, Teynampet', latitude: 13.04372, longitude: 80.25014, phoneNumber: '+914424567890', cuisineType: ['Indian', 'Vegan'], priceRange: 2, rating: 4.3, totalReviews: 95, description: 'South Indian vegan delights with a modern twist', tags: ['south-indian', 'vegan', 'dine-in'], source: 'google', isVerified: true },
      { name: 'Lotus Vegan Kitchen', city: 'Chennai', state: 'Tamil Nadu', address: '88, TTK Road, Alwarpet', latitude: 13.03421, longitude: 80.25627, phoneNumber: '+914428901234', cuisineType: ['Asian', 'Vegan'], priceRange: 3, rating: 4.7, totalReviews: 210, description: 'Pan-Asian vegan cuisine in an elegant setting', tags: ['asian', 'fine-dining', 'rooftop'], source: 'google', isVerified: true },
      { name: 'Sprout & Soul', city: 'Chennai', state: 'Tamil Nadu', address: '34, ECR, Thiruvanmiyur', latitude: 12.98345, longitude: 80.26174, phoneNumber: '+914424561111', cuisineType: ['Salads', 'Smoothies', 'Vegan'], priceRange: 2, rating: 4.4, totalReviews: 76, description: 'Fresh bowls, smoothies, and raw vegan options', tags: ['healthy', 'smoothies', 'bowls'], source: 'manual', isVerified: true },
      { name: 'Bhumi Kitchen', city: 'Chennai', state: 'Tamil Nadu', address: '5, Besant Nagar 3rd Ave', latitude: 13.00012, longitude: 80.26789, phoneNumber: '+914424562222', cuisineType: ['Indian', 'Vegan', 'Organic'], priceRange: 1, rating: 4.1, totalReviews: 52, description: 'Budget-friendly organic vegan meals', tags: ['budget', 'organic', 'tiffin'], source: 'manual', isVerified: false },
      { name: 'Herbivore Haven', city: 'Chennai', state: 'Tamil Nadu', address: '22, Velachery Main Rd', latitude: 12.97812, longitude: 80.22134, phoneNumber: '+914424563333', cuisineType: ['Continental', 'Vegan'], priceRange: 2, rating: 4.2, totalReviews: 88, description: 'European-inspired plant-based bistro', tags: ['continental', 'bistro', 'wine'], source: 'google', isVerified: true },
      { name: 'Raw & Co', city: 'Chennai', state: 'Tamil Nadu', address: '67, Cathedral Rd, Gopalapuram', latitude: 13.05234, longitude: 80.25912, phoneNumber: '+914424564444', cuisineType: ['Raw', 'Vegan', 'Juices'], priceRange: 3, rating: 4.5, totalReviews: 134, description: 'Raw vegan and cold-pressed juice bar', tags: ['raw', 'juice-bar', 'detox'], source: 'google', isVerified: true },
      { name: 'The Vegan Joint', city: 'Chennai', state: 'Tamil Nadu', address: '9, OMR, Sholinganallur', latitude: 12.90145, longitude: 80.22789, phoneNumber: '+914424565555', cuisineType: ['Mexican', 'Vegan'], priceRange: 2, rating: 4.0, totalReviews: 45, description: 'Vegan burritos, tacos, and nachos', tags: ['mexican', 'casual', 'takeaway'], source: 'manual', isVerified: false },
      { name: 'Seeds & Stems', city: 'Chennai', state: 'Tamil Nadu', address: '101, Poonamallee High Rd, Kilpauk', latitude: 13.08456, longitude: 80.23567, phoneNumber: '+914424566666', cuisineType: ['Indian', 'Vegan'], priceRange: 1, rating: 3.9, totalReviews: 33, description: 'Traditional South Indian meals, fully vegan', tags: ['meals', 'thali', 'budget'], source: 'manual', isVerified: false },
      { name: 'Zen Garden Vegan', city: 'Chennai', state: 'Tamil Nadu', address: '15, Harrington Rd, Chetpet', latitude: 13.07234, longitude: 80.24612, phoneNumber: '+914424567777', cuisineType: ['Chinese', 'Japanese', 'Vegan'], priceRange: 3, rating: 4.4, totalReviews: 167, description: 'Zen-themed Asian vegan dining experience', tags: ['zen', 'asian', 'peaceful'], source: 'google', isVerified: true },
      { name: 'Plant Power Cafe', city: 'Chennai', state: 'Tamil Nadu', address: '38, Chamiers Rd, RA Puram', latitude: 13.02987, longitude: 80.25345, phoneNumber: '+914424568888', cuisineType: ['Cafe', 'Vegan', 'Bakery'], priceRange: 2, rating: 4.3, totalReviews: 112, description: 'Vegan bakery and coffee shop', tags: ['cafe', 'bakery', 'coffee'], source: 'google', isVerified: true },
      { name: 'Terra Verde', city: 'Chennai', state: 'Tamil Nadu', address: '77, Mount Rd, Guindy', latitude: 13.01234, longitude: 80.21567, phoneNumber: '+914424569999', cuisineType: ['Italian', 'Vegan'], priceRange: 3, rating: 4.6, totalReviews: 189, description: 'Authentic Italian flavors, completely plant-based', tags: ['italian', 'pasta', 'pizza'], source: 'google', isVerified: true },
      { name: 'Annam Vegan', city: 'Chennai', state: 'Tamil Nadu', address: '200, GST Rd, Chromepet', latitude: 12.95123, longitude: 80.14234, phoneNumber: '+914424560001', cuisineType: ['Indian', 'Vegan'], priceRange: 1, rating: 4.0, totalReviews: 67, description: 'South Indian vegan meals at pocket-friendly prices', tags: ['meals', 'south-indian', 'affordable'], source: 'manual', isVerified: false },
      { name: 'Millet Magic', city: 'Chennai', state: 'Tamil Nadu', address: '56, Adyar Main Rd', latitude: 13.00567, longitude: 80.25678, phoneNumber: '+914424560002', cuisineType: ['Indian', 'Millet', 'Vegan'], priceRange: 2, rating: 4.2, totalReviews: 91, description: 'Millet-based vegan cuisine for health-conscious diners', tags: ['millet', 'healthy', 'gluten-free'], source: 'google', isVerified: true },
      { name: 'Buddha Bowl Chennai', city: 'Chennai', state: 'Tamil Nadu', address: '3, Boat Club Rd, RA Puram', latitude: 13.03345, longitude: 80.26012, phoneNumber: '+914424560003', cuisineType: ['Bowls', 'Vegan', 'Health Food'], priceRange: 2, rating: 4.5, totalReviews: 143, description: 'Nourishing buddha bowls with fresh local produce', tags: ['bowls', 'healthy', 'instagram'], source: 'google', isVerified: true },
      // Mumbai — 8 restaurants
      { name: 'Vegan Bites Mumbai', city: 'Mumbai', state: 'Maharashtra', address: '14, Carter Rd, Bandra West', latitude: 19.06234, longitude: 72.83456, phoneNumber: '+912226541234', cuisineType: ['Indian', 'Vegan'], priceRange: 2, rating: 4.4, totalReviews: 203, description: 'Trendy vegan spot in the heart of Bandra', tags: ['trendy', 'bandra', 'delivery'], source: 'google', isVerified: true },
      { name: 'The Green Bowl', city: 'Mumbai', state: 'Maharashtra', address: '8, Hill Rd, Bandra West', latitude: 19.05789, longitude: 72.83012, phoneNumber: '+912226545678', cuisineType: ['Bowls', 'Salads', 'Vegan'], priceRange: 2, rating: 4.3, totalReviews: 156, description: 'Customizable plant-based bowls and salads', tags: ['bowls', 'salads', 'healthy'], source: 'google', isVerified: true },
      { name: 'Earthen Vegan', city: 'Mumbai', state: 'Maharashtra', address: '45, Linking Rd, Santacruz', latitude: 19.08345, longitude: 72.83789, phoneNumber: '+912226549012', cuisineType: ['Indian', 'Vegan', 'Thali'], priceRange: 1, rating: 4.1, totalReviews: 89, description: 'Traditional thali meals, all plant-based', tags: ['thali', 'traditional', 'budget'], source: 'manual', isVerified: false },
      { name: 'Prana Cafe', city: 'Mumbai', state: 'Maharashtra', address: '23, Juhu Tara Rd', latitude: 19.10234, longitude: 72.82567, phoneNumber: '+912226543456', cuisineType: ['Cafe', 'Vegan', 'Gluten-Free'], priceRange: 3, rating: 4.6, totalReviews: 178, description: 'Upscale vegan cafe with ocean views', tags: ['ocean-view', 'upscale', 'brunch'], source: 'google', isVerified: true },
      { name: 'Plant Lab', city: 'Mumbai', state: 'Maharashtra', address: '12, Colaba Causeway', latitude: 18.92134, longitude: 72.83234, phoneNumber: '+912226547890', cuisineType: ['Continental', 'Vegan'], priceRange: 3, rating: 4.5, totalReviews: 234, description: 'Experimental plant-based fine dining', tags: ['fine-dining', 'experimental', 'cocktails'], source: 'google', isVerified: true },
      { name: 'Ahimsa Kitchen', city: 'Mumbai', state: 'Maharashtra', address: '67, SV Rd, Andheri West', latitude: 19.11567, longitude: 72.84012, phoneNumber: '+912226541111', cuisineType: ['Indian', 'Jain', 'Vegan'], priceRange: 1, rating: 4.0, totalReviews: 72, description: 'Jain and vegan friendly pure vegetarian kitchen', tags: ['jain', 'pure-veg', 'affordable'], source: 'manual', isVerified: false },
      { name: 'Sage & Thyme', city: 'Mumbai', state: 'Maharashtra', address: '91, Turner Rd, Bandra', latitude: 19.05912, longitude: 72.83567, phoneNumber: '+912226542222', cuisineType: ['Mediterranean', 'Vegan'], priceRange: 3, rating: 4.7, totalReviews: 198, description: 'Mediterranean plant-based cuisine with rooftop seating', tags: ['mediterranean', 'rooftop', 'date-night'], source: 'google', isVerified: true },
      { name: 'Roots Mumbai', city: 'Mumbai', state: 'Maharashtra', address: '34, Waterfield Rd, Bandra', latitude: 19.06567, longitude: 72.83123, phoneNumber: '+912226543333', cuisineType: ['Vegan', 'Organic', 'Farm-to-table'], priceRange: 2, rating: 4.3, totalReviews: 121, description: 'Farm-to-table organic vegan experience', tags: ['organic', 'farm-to-table', 'sustainable'], source: 'google', isVerified: true },
      // Bangalore — 4 restaurants
      { name: 'Green Theory', city: 'Bangalore', state: 'Karnataka', address: '78, Indiranagar 12th Main', latitude: 12.97345, longitude: 77.64012, phoneNumber: '+918041234567', cuisineType: ['Indian', 'Vegan', 'Organic'], priceRange: 2, rating: 4.5, totalReviews: 267, description: 'Popular organic vegan restaurant in Indiranagar', tags: ['organic', 'popular', 'indiranagar'], source: 'google', isVerified: true },
      { name: 'Paradigm Shift', city: 'Bangalore', state: 'Karnataka', address: '22, Koramangala 4th Block', latitude: 12.93456, longitude: 77.62789, phoneNumber: '+918041238901', cuisineType: ['Vegan', 'Continental', 'Cafe'], priceRange: 2, rating: 4.4, totalReviews: 189, description: 'Vegan cafe with artisanal coffee and brunch', tags: ['cafe', 'brunch', 'artisanal'], source: 'google', isVerified: true },
      { name: 'Seeds of Life', city: 'Bangalore', state: 'Karnataka', address: '55, HSR Layout Sector 2', latitude: 12.91234, longitude: 77.63456, phoneNumber: '+918041232345', cuisineType: ['Raw', 'Vegan', 'Juices'], priceRange: 2, rating: 4.2, totalReviews: 98, description: 'Raw food and cold-pressed juices', tags: ['raw', 'juices', 'healthy'], source: 'manual', isVerified: true },
      { name: 'The Vegan Trove', city: 'Bangalore', state: 'Karnataka', address: '11, MG Rd, Brigade Gateway', latitude: 12.97567, longitude: 77.60345, phoneNumber: '+918041236789', cuisineType: ['Multi-cuisine', 'Vegan'], priceRange: 3, rating: 4.6, totalReviews: 312, description: 'Multi-cuisine vegan fine dining on MG Road', tags: ['fine-dining', 'multi-cuisine', 'central'], source: 'google', isVerified: true },
      // Gurgaon — 3 restaurants
      { name: 'Plant Powered Gurgaon', city: 'Gurgaon', state: 'Haryana', address: '45, Cyber Hub, DLF Phase 2', latitude: 28.49456, longitude: 77.08912, phoneNumber: '+911241234567', cuisineType: ['Vegan', 'Health Food'], priceRange: 3, rating: 4.5, totalReviews: 156, description: 'Premium vegan dining at Cyber Hub', tags: ['cyber-hub', 'premium', 'corporate'], source: 'google', isVerified: true },
      { name: 'Veg Voyage', city: 'Gurgaon', state: 'Haryana', address: '12, Sector 29 Market', latitude: 28.46234, longitude: 77.06345, phoneNumber: '+911241238901', cuisineType: ['Indian', 'Vegan', 'Street Food'], priceRange: 1, rating: 4.1, totalReviews: 87, description: 'Vegan street food and chaats', tags: ['street-food', 'chaat', 'casual'], source: 'manual', isVerified: false },
      { name: 'Nourish Cafe', city: 'Gurgaon', state: 'Haryana', address: '8, Golf Course Rd, DLF Phase 5', latitude: 28.44567, longitude: 77.10234, phoneNumber: '+911241232345', cuisineType: ['Cafe', 'Vegan', 'Bakery'], priceRange: 2, rating: 4.3, totalReviews: 134, description: 'Vegan bakery and specialty coffee', tags: ['bakery', 'coffee', 'cozy'], source: 'google', isVerified: true },
    ];

    await this.repository.save(this.repository.create(restaurants));
  }
}
